#!/usr/bin/env bash
# Create a hardened seed-oriented ~/.ega/ega.conf (no public RPC).
# Usage: bash scripts/setup-seed-node.sh [optional_home_peer_ip]
set -euo pipefail
DATADIR="${EGA_DATADIR:-$HOME/.ega}"
PEER="${1:-}"
mkdir -p "$DATADIR"
CONF="$DATADIR/ega.conf"

PASS="${EGA_RPC_PASSWORD:-$(head -c 24 /dev/urandom | xxd -p)}"
if [[ -f "$CONF" ]]; then
  echo "Exists: $CONF"
  echo "Refusing to overwrite. Move it aside or edit manually."
  exit 1
fi

cat > "$CONF" << EOF
# EGA seed / public node — generated by setup-seed-node.sh
server=1
listen=1
txindex=1

port=20201
rpcport=20202
rpcbind=127.0.0.1
rpcallowip=127.0.0.1
rpcuser=ega
rpcpassword=${PASS}

# Optional peer (home PC or Oracle)
EOF

if [[ -n "$PEER" ]]; then
  echo "addnode=${PEER}:20201" >> "$CONF"
fi

chmod 600 "$CONF"
echo "Wrote $CONF"
echo "RPC password stored in conf (mode 600)."
echo "Open firewall TCP 20201 only. Do not expose 20202."
echo "Start: egad -daemon   (or systemctl enable --now egad)"
