#!/usr/bin/env bash
# Prepare a light/pruned EGA node config (Android Termux, Pi, weak PC).
# Usage: bash scripts/setup-android-node.sh [seed_ip]
set -euo pipefail
SEED="${1:-105.225.132.175}"
DATADIR="${EGA_DATADIR:-$HOME/.ega}"
mkdir -p "$DATADIR"
CONF="$DATADIR/ega.conf"
PASS="${EGA_RPC_PASSWORD:-$(head -c 12 /dev/urandom | xxd -p)}"

if [[ -f "$CONF" ]]; then
  echo "Config exists: $CONF"
  echo "Not overwriting. Edit manually or move it aside."
  exit 1
fi

cat > "$CONF" << EOF
# EGA light/pruned node — generated by setup-android-node.sh
server=1
listen=1
txindex=0
prune=1024
dbcache=100
maxconnections=8
listenonion=0

rpcuser=ega
rpcpassword=${PASS}
rpcbind=127.0.0.1
rpcallowip=127.0.0.1
rpcport=20202
port=20201

addnode=${SEED}:20201
algo=yespower-ega
EOF
chmod 600 "$CONF"
echo "Wrote $CONF"
echo "Seed peer: ${SEED}:20201"
echo "Start: ./src/egad -daemon"
echo "Check: ./src/ega-cli getconnectioncount"
echo "See: docs/ega/ANDROID-LIGHT-NODE.md"
